import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <main
            className={
              "bg-slate-200 flex min-h-screen flex-col items-center justify-center p-10"
            }
          >
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
